defaultTheme: auto
description: Acesyde tech blog
keywords:
  - blog
  - tech
  - AWS
  - dotnet
author:
  - Pierre-Emmanuel MERCIER
ShowReadingTime: true
ShowShareButtons: true
ShowPostNavLinks: true
ShowBreadCrumbs: true
ShowToc: true
ShowCodeCopyButtons: true
comments: false

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai

profileMode:
  enabled: false

homeInfoParams:
  Title: ğŸ‘‹, here and welcome to my tech blog
  Content: >
    - ğŸ–¥ï¸ I'm a Software Architect

    - ğŸ£ Iâ€™m currently working at Betclic Group (Gambling Company)

    - ğŸ  I live in France
    
    - ğŸ’¬ Ask me about .NET, Docker, AWS, Azure

socialIcons:
  - name: twitter
    url: "https://twitter.com/lim_ace"
  - name: linkedin
    url: "https://www.linkedin.com/in/pierre-emmanuel-mercier-10b82a37/"
  - name: github
    url: "https://github.com/acesyde"
  - name: rss
    url: "https://blog.ace-dev.fr/sitemap.xml"
  - name: mastodon
    url: "https://mastodon.top/@Acesyde"
