
[settings]
experimental = true

[settings.npm]
package_manager = "pnpm"

[tasks.build]
description = "Build the site"
run = "hugo build --minify"

[tasks.serve]
description = "Serve the site"
run = "hugo serve"

[tasks.theme-install]
description = "Install the theme"
run = "git submodule update --init --recursive"

[tasks.theme-update]
description = "Update the theme"
run = "git submodule update --remote --merge"

[tools]
node = "24.11.1"
"npm:astro" = "5.16.9"
pnpm = "10.28.0"
